apiVersion: storage.k8s.io/v1beta1
kind: CSIDriver
metadata:
  name: pmem-csi.intel.com
spec:
  attachRequired: false
  podInfoOnMount: true
  storageCapacity: true # Alpha feature!
  volumeLifecycleModes:
  - Persistent
  - Ephemeral
