# Turns generic Kubernetes 1.19 deployment into deployment for direct mode.

bases:
- ../kubernetes-1.19/

commonLabels:
  pmem-csi.intel.com/deployment: direct-production

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: DaemonSet
    name: pmem-csi-node
  path: ../patches/direct-patch.yaml
